### ISSUE TITLE
update version numbers

### ISSUE THREAD

**Issue by dimbleby** [c-ares/c-ares#115]
c-ares version 1.13.0 is [apparently released](https://c-ares.haxx.se/mail/c-ares-archive-2017-06/0003.shtml), but is still [versioned](https://github.com/c-ares/c-ares/blob/3be1924221e1326df520f8498d704a5c4c8d0cce/ares_version.h#L9-L14) as 1.12.1-dev

**Comment by daviddrysdale** [comment]
The [released tarball](https://c-ares.haxx.se/download/c-ares-1.13.0.tar.gz) has 1.13.0 in `ares_version.h` but you're right, it would be nice to update the checked in version too.

**Comment by dimbleby** [comment]
> The released tarball has 1.13.0 in ares_version.h

Well, that's a relief!  

Still, the contents of the tarball really ought to match with the git tag `cares-1_13_0`.  

I was pretty surprised to check out that code and find that the version as reported by `ares_version()` was *not* 1.13.0...

**Comment by bagder** [comment]
The release of c-ares is what maketgz produces at the time of the tag.

**Comment by dimbleby** [comment]
Well yes, but... maketgz requires that you enter the version number, then the build process does some slightly baroque stuff, and at the end of it all the code that is shipped in the tarball does not match the code in the repository.

It's not exactly earth-shattering: but do we agree that it's at least somewhat confusing for the code that's tagged as `cares-1.13.0` to compile as some other version?

If your position is that this is a non-issue then so be it: let's agree to differ and close this out.

But if you agree that this is at least a bit confusing, then we can talk about ways in which to avoid it...

**Comment by bagder** [comment]
I'd agree that it is a minor issue, yes. But I also consider it a minor issue when people assume that everything that is in a git repository with a tag then automatically is exactly what is in a release tarball.

We commit and and we version control everything that isn't otherwise generated from version controlled sources, so that we always can reproduce every version after the fact. This includes the version number header file, as that's updated carefully by the tarball-making script. **The release is the tarball**. The tag in git is not the release, it's just the marker for that moment in time for everything in the repo that was used in the release tarball.

If you want to exactly reproduce a release build, you need generate the files the same way as was done to make the release.

The `ares_version.h` header in git is meant to (primarily) say "version [NEXT]-dev` (where NEXT is the planned coming release version number) so that when you build from git and run it, it is visible that it is the development version of the next release. So immediately following each release, we should bump that number in git so that our own dev builds keep showing that they are development versions of the next version.

**Comment by dimbleby** [comment]
Understood.

Nevertheless... how would you feel about a patch that added something to `maketgz` - a reminder that it would be appreciated if you could commit a suitably versioned `ares_version.h` before delivering?

Something like this:

```perl
my $changed = system("diff ares_version.h ares_version.h.dist > /dev/null");
if ($changed) {
    die "please commit updated ares_version.h before releasing"
}
```

**Comment by daviddrysdale** [comment]
Maybe it would also be worth writing down a release checklist somewhere?  Stuff like:
 - update `RELEASE-NOTES` for the new release (is that manual or is there a job to help?)
 - create a release tarball by running `maketgz` with the new version number, e.g. `maketgz 1.14.0`
 - tag the corresponding code with something like `git tag cares-1_14_0`
 - upload the tarball to https://c-ares.haxx.se/download/
 - change the version in `ares_version.h` to reflect development of the next release, e.g. `1.15.0-dev`
 - push the changes to GitHub, including the new tag

(As it happens, I'm with @dimbleby on the version confusion -- I think it would be nice if `git checkout cares-1_13_0` gave code that was version-labelled the same as the official tarball)

**Comment by bagder** [comment]
A "Release process" document or checklist like that would be great I think.

Let me write up a first version and then you can suggest improvements/edits to it.

**Comment by bagder** [comment]
There!

**Comment by dimbleby** [comment]
Having a process written down seems very sensible: but the process you've defined doesn't address the issue that we're discussing here!

Assuming you're open to doing so, suggest something like:
* have `maketgz` copy the new `ares_version.h` into place
* commit that file and tag the code *after* running `maketgz` rather than before
* (that's it).

what do you think?

**Comment by bagder** [comment]
You're then arguing that we should commit (and tag) `ares_version.h` to git as it looks in the release tarball, which I didn't say and I didn't write in the release procedure documentation. Correct.

What's the benefit of doing that? Make people build a "release" from git code that isn't exactly the same as what we released but still claim it is the release?

**Comment by bagder** [comment]
I suppose what I'm saying is that exactly when the release is done, what's in git is the first work on the next version.

**Comment by dimbleby** [comment]
I thought we'd agreed that it was a little confusing for the version number in the tagged code to disagree with the tag?

I'd imagined that `ares_version.h` would change twice during the release process:
* once (briefly) to the version being released, for the benefit of the tagged code
* then to the next dev version

I didn't expect this issue to be controversial!  If you think that what I'm trying to achieve is not useful, or is more trouble than it's worth, please just close the issue out.
