### ISSUE TITLE
resolve so slow at android platform

### ISSUE THREAD

**Issue by halx99** [c-ares/c-ares#185]
device: xiaomi5s, miui9, 114.114.114.114, but at windows platform, same network, it's fast.

**Comment by bradh352** [comment]
please provide more information.
Android version
c-ares version
code being used, etc

**Comment by halx99** [comment]
android  version is 7.0
c-ares version is latest github with ares_getaddrinfo PR
code being used is here: https://github.com/halx99/xxsocket/blob/master/src/async_tcp_client.cpp

**Comment by idcrisis** [comment]
TCP socket takes a second each time to open the port.

They may have a Async UDP query feature.

Also connection reuse TCPIP parameter might help. Either in the OS or the
source code. Or both.

By no means an expert but they should keep four ports open and reuse
internally. Like a poor man's port queue.

Embedded zero copy TCPIP stacks are also sorely required.

Cheers.

**Comment by bagder** [comment]
@idcrisis: those are suggestions for general TCP speedup improvements, sure (and I'm sure we'd welcome PRs that makes c-ares do better), but not necessarily a good explanation why Android would be slower than anything else.

> Embedded zero copy TCPIP stacks are also sorely required

For the tiny DNS request and responses c-ares works with, I would seriously doubt that you can even measure a notable time difference on modern hardware.

**Comment by halx99** [comment]
Does this issue  have any solution?

**Comment by bradh352** [comment]
DNS resolution is fast for me on Android with c-ares.  Perhaps you can provide more information, such as if your device has an IPv6 address or similar, and what DNS servers are configured.  I also do not use the ares_getaddrinfo PR, and since that is not a core feature of c-ares yet, cannot support its use at this time.

I glanced at your code, and I did notice a couple of things.  First, I'm not seeing ares_library_init_android()  being called which is required on modern android releases.  Next, it doesn't appear you're calling ares_timeout() and you're just blocking in your select() call for some unknown amount of time.  You *must* call ares_timeout() to get the amount of time to wait before you at least need to call ares_process() with no FDs if none were triggered.  This is how c-ares handles things like timing out and re-trying other DNS servers.  I'd bet this is the root of your problem.

**Comment by halx99** [comment]
I just call  ares_library_init_android() at java, and got 3 dns server:
101.37.15.12
223.5.5.5
223.6.6.6

OK, I will do some fixs what you said, and try again.

**Comment by halx99** [comment]
@bradh352 Hi, it's great, I have made some fixes, and try again, it's seems work fine.
https://github.com/halx99/xxsocket/blob/master/src/async_tcp_client.cpp
Thanks for your response. very thanks.

**Comment by halx99** [comment]
But some time, it's slow than system getaddrinfo; some other time, it's fast.
