### ISSUE TITLE
MSVC default static library output file no "lib" prefix

### ISSUE THREAD

**Issue by rixtox** [c-ares/c-ares#203]
I build with the following settings:

```
cmake -DCMAKE_INSTALL_PREFIX="%PREFIX%" -DCARES_STATIC=ON -DCARES_SHARED=OFF -G "Visual Studio 15 2017 Win64" ..
cmake --build . --config Release --target INSTALL
```

The installed static lib file was `cares.lib`. By convention, static windows libraries should have `lib` prefix, in this case the file name should be `libcares.lib`.

Build scripts following the convention couldn't resolve to the generated lib by default, e.g. curl.

**Comment by gvanem** [comment]
What *convention* is this and where is that documented? Look very backwards compared to other conventions where:
* Import libraries are named `foo_imp.lib`. Pretty clear from the name that it's a import-lib, no?
* Static libraries are named `foo.lib`

**Comment by rixtox** [comment]
I don't recall the original documentation but Boost has mentioned it here:
https://www.boost.org/doc/libs/1_42_0/more/getting_started/windows.html
In section 6.3.

**Comment by rixtox** [comment]
Here's the build script for curl where you can see the logic of the convention:

https://github.com/curl/curl/blob/master/winbuild/MakefileBuild.vc#L202-L218

Just as explained by Boost:

> This convention distinguishes the static version of a Boost library from the import library for an identically-configured Boost DLL, which would otherwise have the same name.

**Comment by bradh352** [comment]
I think changing this would break existing integrations that rely on current behavior.

**Comment by am11** [comment]
> What _convention_ is this and where is that documented?

I know it is an old question, but since I was also struggling to figure it out, I wanted to share my findings.

In msvc world, when we compile a shared library say `foo.dll`, it also creates something called "import library" `foo.lib` next to `foo.dll`. It is just a convenient wrapper of `foo.dll`, listing it dependencies and where to find them etc. (ref: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation).

However, the "import library" is not the same thing as "static library", but unfortunately they share the same file extension `.lib`. To disambiguate the two by name, a convention sometimes used in the wild is to prefix the "static library" as in: `libfoo.lib` and leave the "import library" unprefixed as in `foo.lib` (next to its associated `foo.dll`).

**Comment by bradh352** [comment]
We really can't make changes without breaking integrations at this point.  This is really a non-issue, any new integrator of c-ares just has to figure out the name they want to link to once ... no big deal.
