### ISSUE TITLE
Test failure with ARES_ECONNREFUSED / Segfault on Azure

### ISSUE THREAD

**Issue by xkszltl** [c-ares/c-ares#253]
Tried in both host and docker on Azure VM.

Host: Ubuntu 18.04 on Azure
Docker: Ubuntu 18.04 / CentOS 7, same error
Compiler: gcc-8.2.1 (devtoolset-8) on CentOS, gcc-8.2.0 on Ubuntu.

More failure in docker comparing to host.

Screenshot attached:

Host:
![image](https://user-images.githubusercontent.com/5203025/57338194-4d661900-70e1-11e9-9e2c-9cc9ea6c35f3.png)

Docker:
![image](https://user-images.githubusercontent.com/5203025/57337692-48a06580-70df-11e9-9768-0a18ba90f78b.png)

Build both shared/static lib.

Investigation:
  - Tried to installed to `/usr/local` and `ldconfig` it to avoid using the wrong lib from distro, but doesn't help.
  - Added `docker run --privileged` but doesn't help.

**Comment by bradh352** [comment]
The live tests, those are always hard as they query real servers on the public internet which can behave differently depending on the recursive resolver being used.

For the docker test, looks like at least part of the issue is due to no IPv6 support in the container.

It just means these test cases probably won't work in azure due to azure-specific things, it doesn't necessarily mean there's anything wrong with your compiled c-ares.  I don't have any azure instances to look into this myself.

**Comment by xkszltl** [comment]
I understand.
Might be better to separate them into 2 test sets, i.e. local and live?

**Comment by ki11roy** [comment]
@xlszltl they are separated, see https://github.com/c-ares/c-ares/blob/master/test/README.md
Moreover you can enable or disable ipv4/ipv6 tests from test/arestest command line. 
Try launch ./arestest -4 (or v4, something like this).

**Comment by xkszltl** [comment]
> @xlszltl they are separated, see https://github.com/c-ares/c-ares/blob/master/test/README.md
> Moreover you can enable or disable ipv4/ipv6 tests from test/arestest command line.
> Try running:
> 
> ```
> ./arestest -v -4
> ```
> 
> and then
> 
> ```
> ./arestest -v -6
> ```
> 
> separately.

Oh thanks! Forgot to mention I'm using CMake.
