### ISSUE TITLE
process_answer without ARES_FLAG_NOCHECKRESP should taking NXDOMAIN into account

### ISSUE THREAD

**Issue by chasel1224** [c-ares/c-ares#271]
Dear Team. I have a dns server list, and the first of which returns "No Such Name", and maybe the second or the third works well. when I use cares in my project, I find it can not skip to next server.
 the problem is that at the end of interface process_answer cares do not taking NXDOMAIN response into account and just end the query instead of skipping the server.
As you know , I need check the reponse, so I do not set ARES_FLAG_NOCHECKRESP.
I hope your team can try my case and help to resolve this. Best regards.

**Comment by bradh352** [comment]
If you want to submit a PR that adds such a flag to try the next server on an NXDOMAIN, then we can entertain it.  Otherwise, NXDOMAIN is an end result and very unusual to try to ignore such a result.  I think DNSMASQ can be used to do this for you, then you'd just configure your system to point to the local DNSMASQ as the nameserver.
