### ISSUE TITLE
RFC conformance of `ares_getaddrinfo` regarding `AI_CANONNAME` and result structures.

### ISSUE THREAD

**Issue by ChristianAmmer** [c-ares/c-ares#286]
An `ares_getaddrinfo` which is compliant regarding input and output (flags, names, result) of the function compared to other `getaddrinfo` implementations would greatly improve acceptence of this function. That should not be underestimated.

In this sense I suggest considering the naming of the `ares_getaddrinfo` result structures and the effect of the flag `ARES_AI_CANONNAME`.

The `ares_getaddrinfo` result structures are

- [`ares_addrinfo_node`](https://github.com/c-ares/c-ares/blob/master/ares.h#L585)
- [`ares_addrinfo_cname`](https://github.com/c-ares/c-ares/blob/master/ares.h#L601)
- [`ares_addrinfo`](https://github.com/c-ares/c-ares/blob/master/ares.h#L608)

The current implementation has the [RFC-3493](https://tools.ietf.org/html/rfc3493) `addrinfo` members stored in `ares_addrinfo_node`. The `ares_addrinfo` on the other hand is a structure which serves as container holding two lists. The first list contains a linked list of CNAME records, and the other contains the real `getaddrinfo` result.
This is confusing. I'm voting for renaming `ares_addrinfo_node` to `ares_addrinfo` and `ares_addrinfo` to some other name e.g. `ares_addrinfo_result`.

Additionally the flag `ARES_AI_CANONNAME` has the effect that a linked list of CNAME records is returned in the result. The RFC-3493 `AI_CANONNAME` on the other hand has following definition: 

>   If nodename is not null, and if requested by the AI_CANONNAME flag,
>   the ai_canonname field of the first returned addrinfo structure shall
>   point to a null-terminated string containing the canonical name
>   corresponding to the input nodename; if the canonical name is not
>   available, then ai_canonname shall refer to the nodename argument or
>   a string with the same contents.  The contents of the ai_flags field
>   of the returned structures are undefined.

Unfortunatelly `ai_canonname` was removed from the ares addrinfo structure and it's also not obvious how to get the RFC `ai_canonname` out of the `ares_addrinfo_cname` structure without deeper knownledge of CNAME chains. I would appreciate if the ares addrinfo structure would include a RFC conformant `ai_canonname` member.

Another point that should be clarified regarding the `getaddrinfo` result is, why should the function return the CNAME record list, I couldn't find an issue asking for this feature, [neither in the c-ares issues](https://github.com/c-ares/c-ares/issues?utf8=%E2%9C%93&q=is%3Aissue+CNAME) nor during a [google search](https://www.google.at/search?q=getaddrinfo+cname). If there is no use case then this list should be removed from the result at all.

**Comment by bradh352** [comment]
The request originated as a TTL discussion, I don't recall where.  But it came to light in order to properly determine the TTL of the actual result, you'd need all the intermediate results TTLs.

I could get on board with renaming ares_addrinfo_node to ares_addrinfo_result, but I think retaining the functionality we have is good.  If there's interest in a more "RFC compliant getaddrinfo" then I'd think we'd expose that separately as a wrapper, and it would probably be conditioned on the system itself already having a struct addrinfo otherwise it won't be exposed.

**Comment by ChristianAmmer** [comment]
I thought about renaming:
- current [`ares_addrinfo_node`](https://github.com/c-ares/c-ares/blob/master/ares.h#L585) to `ares_addrinfo`
- current [`ares_addrinfo`](https://github.com/c-ares/c-ares/blob/master/ares.h#L608) to `ares_addrinfo_result`
- remove [`ares_addrinfo_hints`](https://github.com/c-ares/c-ares/blob/master/ares.h#L613) (it's a copy of `ares_addrinfo_node` with lesser properties).

And also making following change:
- add `ai_canonname` to `ares_addrinfo` and set the property like it's defined in RFC

`ares_getaddrinfo` would become more RFC conformant and still retain the [`ares_addrinfo_cname`](https://github.com/c-ares/c-ares/blob/master/ares.h#L601) result.

I don't get the thing with the TTL, why are the intermediate results needed? @bradh352 do you have a reference for this – I would realy like to understand this better?

**Comment by bradh352** [comment]
The ttl is all about caching middleware, I'm not sure if there's any other usecase.   Which would mean possibly just saving the lowest ttl in the result would be sufficient for that case.  

Your proposal for renaming, so just the first result would have the ai_canonname pointer to the list?  Not sure exactly what's being proposed.

**Comment by ChristianAmmer** [comment]
If the lowest ttl is sufficient and this value is available in the `ai_ttl` member of the first returned [`ares_addrinfo`](https://github.com/c-ares/c-ares/blob/master/ares.h#L585) structure, then `ares_addrinfo_cname` isn't needed anymore?

Yes, `ai_canonname` member should contain the canonical name in the first returned `ares_addrinfo` structure. Like its defined in RFC and quoted in the issue description.

**Comment by bradh352** [comment]
I'm not comfortable being the only person to chime in on that, as there may be use cases I'm not aware of.  @bagder @ki11roy care to comment?

I could see people wanting the entire cname chain, however whether they need the ttl of every entry in the chain vs just the lowest, I can't really comment on.

I guess the first member of the list could always have members more like.

`...
unsigned int ai_ttl;
char **ai_canonnamelist;
size_t ai_canonnamelist_len;
const char *ai_canonname = ai_canonnamelist[0];
...
`

**Comment by ki11roy** [comment]
> If the lowest ttl is sufficient and this value is available in the `ai_ttl` member of the first returned [`ares_addrinfo`](https://github.com/c-ares/c-ares/blob/master/ares.h#L585) structure, then `ares_addrinfo_cname` isn't needed anymore?

This will put the responsibility of getting the right (lowest in this case) value back to the library and there will be no way to know the other TTLs.
There were some requests like #238 and #259 behind that decision. Also this will complicate parsing process.

> If yes, I propose to completly remove `ares_addrinfo_cname` (because not needed), rename `ares_addrinfo_node` to `ares_addrinfo` and remove `ares_addrinfo_hints` (because same members are available in `ares_addrinfo`).
> And yes, `ai_canonname` member should contain the canonical name in the first returned `ares_addrinfo` structure. Like its defined in RFC and quoted in the issue description.

Can’t agree with it as I see no real purpose in being complaint with that particular part of the RFC by the price of reducing the functionality. The function is called ares_getaddrinfo and not getaddrinfo right?

That thing with the first cname looks like an optimization and quite an ugly one, because you are not using all the cname pointers besides the first one. Also, you are losing all the aliases from the gethostbyname.

**Comment by ki11roy** [comment]
> I'm not comfortable being the only person to chime in on that, as there may be use cases I'm not aware of. @bagder @ki11roy care to comment?

I can recall #238 and #259 

> I could see people wanting the entire cname chain, however whether they need the ttl of every entry in the chain vs just the lowest, I can't really comment on.

Can’t invent such a purpose either. However with the struct you are having all the TTLs automatically as it is easier to parse into such a structure.

> I guess the first member of the list could always have members more like.
> 
> `...`
> `unsigned int ai_ttl;`
> `char **ai_canonnamelist;`
> `size_t ai_canonnamelist_len;`
> `const char *ai_canonname = ai_canonnamelist[0];`
> `...`

Well, having that in every element of the list looks a bit strange to me (can’t say for everyone though). And this one is not RFC compliant anyway, however a less radical change than with the structures...

**Comment by ChristianAmmer** [comment]
No, I was misunderstood I don't wrote that the first cname record should be the value for `ai_canonname`. But the first `ai_canonname ` should contain the "real" canonical name and therefore the full chain has to be followed. I found [this description](https://stackoverflow.com/a/56856437) which describes it good (imo):
> A canonical name is the final name after following zero or more CNAME records.

The function is called `ares_getaddrinfo` without the "ares_" namespace it's identical to the RFC function, it was also written by us (at least began by me) in the mind of this RFC definition. And users of c-ares will expect similar behavior, similar input and similar output. If the cname chain is also a purpose then possibly another function should be added to solve this purpose.

> and there will be no way to know the other TTLs.

What is the use case for knowing the other TTLs, what is the use case for knowing the cname chain? If there is no such use case, I'm again voting for removing it from the result. This makes it more RFC conformant.

**Comment by bradh352** [comment]
We have objections from others, and I tend to agree with them.

RFC conformance from an API level I don't think means anything as long as documentation is correct.  People aren't converting code from `getaddrinfo()` to `ares_getaddrinfo()` directly due to the already-existing API incompatibilities with it being callback-based. RFC conformance could be seen as a minimum benchmark from a functionality/feature standpoint, however.  Indeed, the only reason to even keep similar naming with the RFC is due to indications of that functionality being comparable, not the API.

We already have the featureset and I think its been agreed by other parties that they are desirable features.  I don't think it makes sense to remove implemented features, and we have other tickets indicating they are already using the said API even though its not in an official release.

If you propose naming changes to structures for simplification or clarification, I think those can be in scope for changes (though would still cause minor breakage as per the above).  I think the only thing we'd accept that would accomplish your actual goal of "RFC Conformance" from an API prototype standpoint would be a *wrapper* to better emulate `getaddrinfo()`, and I'd think that wrapper should rely on the system's `struct addrinfo` if it exists, or the wrapper as a whole would not be available.  This wrapper would be fairly cheap as it would really just rewrite the response into the system's format, though care would need to be taken to ensure it can be cleaned up via the system's `freeaddrinfo()`, and thus not use `ares_malloc()` or similar.

**Comment by ChristianAmmer** [comment]
@bradh352 thank you for your answer. It's a decision which I don't like but where we can build on.

Please accept that I still want to share my concerns about this decision: Adding the cname list to the result increased the number of `getaddrinfo` structures, the user has to deal with, from 1 to 4. This cname list is supposed to be an additional feature and a replacement for the member `ai_canonname`, but it actually transfers the overhead of working out the canonical name from the library to the user. The cname-list-feature is nevertheless – for not explained reasons – considered as desirable.

- About renamings: Yes, I think it would make sense, I will make a PR as discussion base.
- About a wrapper: I think it's a very good idea to create a function which builds on the system's `struct addrinfo` if it exists and the function being only available in this case.

**Comment by ki11roy** [comment]
@ChristianAmmer so-called cname-list-feature is actually alias feature, which you can find in the hostent structure and which was removed from addrinfo for some reason. 

See this threads:
 - https://groups.google.com/forum/m/#!topic/microsoft.public.platformsdk.networking.ipv6/yOgW7FbZ1N4
 - https://stackoverflow.com/questions/35762066/resolve-fqdn-but-not-necessarily-canonical-name-with-getaddrinfo

**Comment by bradh352** [comment]
API/ABI is now set with the 1.16.0 release, so we can't make any changes ... other than adding a new wrapper API to use the systems addrinfo struct.
