### ISSUE TITLE
CNAME with no associated A record returns success status

### ISSUE THREAD

**Issue by tjwalton** [c-ares/c-ares#303]
I have a DNS record which returns a CNAME pointing to a non-existent domain: an example is `broken.thomaswalton.co.uk`.

Using `ares_gethostbyname` with an A record request for this domain returns a status of `ARES_SUCCESS` even though no record was found.  The status should surely be `ARES_ENODATA` instead.

This can be fixed by something like https://github.com/tjwalton/c-ares/commit/06fcfd0a49f1c2bf4884d42e86c64fcb7c551a03 but I suspect something more nuanced may be better.

**Comment by tjwalton** [comment]
This should be tested by https://github.com/c-ares/c-ares/blob/master/test/ares-test-parse-a.cc#L133 but the test is broken due to missing a `data = pkt.data();` at this point.

**Comment by bradh352** [comment]
From mailing list:
> Hello,
>
> I have created https://github.com/c-ares/c-ares/issues/303 because c-ares returns a SUCCESS status when it just receives a CNAME in response to a query (with no A or AAAA name provided).  I consider this to be a bug, and clearly the test at https://github.com/c-ares/c-ares/blob/b9eb3a0cfe7f50a3eaa8a1755ae57f7657931e3e/test/ares-test-parse-a.cc#L134 was supposed to check this, but the test is broken and doesn't work.  When the test is corrected, it fails.  However, this then clashes with test ParseAReplyJustCname, which is essentially testing the same case and checking for a different result.
>
> However, there is a comment in the code implying that this behaviour of returning a success for a CNAME only lookup is intentional.  This was added in https://github.com/c-ares/c-ares/commit/2c63440127feed70ccefb148b8f938a2df6c15f8 many years ago.
> 
> What is the intended behaviour of c-ares in cases like this?  How should CNAME queries be handled?  Is there even a good way of reconciling these two requirements?
>
> I am happy to try to write a patch for this issue, but I do not want to break existing useful behaviour.
>
> Regards,
>
> Thomas

**Comment by bradh352** [comment]
It looks like the nodejs guys needed parse_a_reply to give them the list of CNAMEs even if they pointed nowhere.  So that seems reasonable.  So your patch also seems reasonable given the behavior, as the behavior for calling gethostbyname() that wraps that stuff needs to then honor the original intent of gethostbyname().

If you want to send a PR with your patch and the test case fix (just add the data = pkt.data() to the test case and change the result expected to ARES_ESUCCESS with a comment that this is intended referencing 2c63440) ... I'll accept it.

Thanks!

**Comment by tjwalton** [comment]
@bradh352: thanks for the comments.  I have now created the above pull request as suggested.
