### ISSUE TITLE
[Suggestion] ares_library_init_android can optimized.

### ISSUE THREAD

**Issue by halx99** [c-ares/c-ares#326]
1. The ConnectivityManager can retrive through jni
2. No need register native API for java to call.

for detail, please see: https://github.com/yasio/yasio/blob/master/yasio/bindings/yasio_jni.cpp

**Comment by bradh352** [comment]
@user-none : looks like halx99 figured out a way to retrieve the connectivity manager using the jvm object

**Comment by user-none** [comment]
Can you provide a link to the official documentation of ActivityThread.currentActivityThread?  I cannot find it listed at developer.android.com. We really can't use anything that is not official supported. The whole point of the Android specific code was due to Android restricting the unofficially supported direct method used on all *nix platforms. We don't want to get into another situation where everything breaks due to Android restricting a call that shouldn't have been used in the first place.

Also, I'm not sure this will work if c-ares is used by a service. ActivityThread.currentActivityThread implies an activity must be running. If a service, which is running in a different address space, is being employed it will not have an activity and shouldn't be able to access the activity thread of the UI application. This should especially true if the service is running in the background and provided by a different application. Since the containing application is not running it shouldn't have an activity thread running to hook into.

**Comment by halx99** [comment]
what about the android.app.AppGlobals

**Comment by user-none** [comment]
You mean [this](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/AppGlobals.java)? Which is marked with `UnsupportedAppUsage` Which is documented as:

```
Indicates that this non-SDK interface is used by apps. A non-SDK interface is a
class member (field or method) that is not part of the public SDK. Since the
member is not part of the SDK, usage by apps is not supported.
```

Also, internally it just calls `ActivityThread`.

**Comment by halx99** [comment]
well, it seems there no official documented API to retrive application context directly

**Comment by halx99** [comment]
but aactivitythread works on app with Acitvity, may be we can try to retrive by ActivityThread.

**Comment by user-none** [comment]
> well, it seems there no official documented API to retrive application context directly

I wasn't able to find anything when I had looked previously. Which is why the external init call is there. I had hoped you found something new or something that I had missed.

> but aactivitythread works on app with Acitvity, may be we can try to retrive by ActivityThread.

Still have the issue of no guarantee on the class/function life. It could go away at any point or be changed in an incompatible manner. Again, this is exactly what happened that necessitated the current code.

Also, apps can provide services to other apps. A background service itself doesn't provide an activity. It will run in a separate address space which should prevent the service from accessing the activity thread entirely. Since it would be in a different address space.

**Comment by halx99** [comment]
please look this article: https://blog.csdn.net/xiaogazhang/article/details/46891139
I'm not sure does it works on service

**Comment by halx99** [comment]
Thanks, I think maybe there is no way to get application context for any android apps, so this issue could be close currently.
I do some optimize the code of ```yasio_jni.cpp```:
1. Try gets from android.app.AppGlobals
2. Try gets from org.yasio.AppGlobals (provide by me), use should call it's init methods to store Context.

refer: https://github.com/yasio/yasio/blob/master/yasio/bindings/java/org/yasio/AppGlobals.java
