### ISSUE TITLE
1.17.1 test fails

### ISSUE THREAD

**Issue by ndowens** [c-ares/c-ares#383]
```
ares-test-live.cc:343: Failure
      Expected: 0
To be equal to: result.status_
      Which is: 12
[  FAILED  ] DefaultChannelTest.LiveSearchANY (5313 ms)
[ RUN      ] DefaultChannelTest.LiveSearchANY_virtualized
ares-test-live.cc:343: Failure
      Expected: 0
To be equal to: result.status_
      Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchANY_virtualized (142 ms)
```

Full test log:
https://termbin.com/r27i is the log output of test failure

**Comment by bradh352** [comment]
Not an issue.  Some DNS servers will reject the LiveSearchANY requests due to a perceived security issue (for instance CloudFlare's 1.1.1.1 is known to do this). 

The FamilyV4ServiceName test relies on getservbyname{_r}() which itself relies on the /etc/services file existing and being valid.  So a failure of that means there's a failure in your system config, which may occur in some containerized environments.

So at the end of the day, these failures are due to your systems config an have nothing to do with the library at all.  If you look at the travis/test.sh you'll see we disable some tests when we automate builds because of these sorts of issues.  If you are automating tests as part of a build/packaging, you should do the same.
