### ISSUE TITLE
inconsistent handling of iphlpapi functions

### ISSUE THREAD

**Issue by dimbleby** [c-ares/c-ares#438]
There's a pile of code in [ares_library_init.c](https://github.com/c-ares/c-ares/blob/65d0d76b014143f2912f161901f765ac6d651cff/src/lib/ares_library_init.c#L73-L101) that dynamically loads `iphlpapi.dll` and discovers whether functions from it are available.

But - per #435 - [ares__system_loopback_addrs](https://github.com/c-ares/c-ares/blob/65d0d76b014143f2912f161901f765ac6d651cff/src/lib/ares__addrinfo_localhost.c#L141-L180) just expects to find `GetUnicastIpAddressTable` and `FreeMibTable`.

This seems inconsistent at best: the older code seems willing to support windows older than Vista, whereas the newer code drops that support.

Was this deliberate?

I don't personally care about running c-ares on old Windows systems; so far as I am concerned it would be fine to drop the dance in the older code.  But this project has historically tended to support a lot of target systems.

**Comment by bradh352** [comment]
Yes, this was intentional.  That dance done in ares_library_init.c was done years and years ago.  We switched to targeting Vista+ by default about 5 years ago.  A developer that may want to still target ancient unsupported releases can still set _WIN32_WINNT to manually target building for said support.

Obviously Vista was EOL back in 2017, and even Windows 7 went EOL early last year.  So that means our current target is 2 EOL releases behind, seems pretty safe.

I would agree that it would make sense to get rid of the legacy code that does runtime checks.  Those are both inefficient and much more complex and harder to maintain.
