### ISSUE TITLE
`ares_library_init` should be thread-safe or even optional

### ISSUE THREAD

**Issue by DemiMarie** [c-ares/c-ares#449]
`ares_library_init` is thread-unsafe, which often forecloses the possibility of using c-ares from within a plugin unless one statically links to c-ares.  It also makes writing safe Rust bindings to c-ares much more difficult.

Since `ares_library_init` does basically nothing nowadays, I suggest making it a no-op.  Presumably, it was intended to cover the case where c-ares was built to use a library that also had a thread-unsafe initializer, such as old versions of OpenSSL.  However, c-ares does not actually use such libraries, and there is a strong trend towards thread-safe or even automatic initialization of libraries in any case.  For instance, OpenSSL initialization has been thread-safe since 1.1.1 if I recall correctly.

**Comment by bradh352** [comment]
C-ares has no concept what-so-ever of threads.  It has always been up to the user to then wrap c-ares in whatever form of thread safety they need.  Your reference to openssl is a bit different as they had globals that would be manipulated at runtime ... nothing like that exists in c-ares, the globals initialized by the library init are used in a read-only fashion.  

The initialization routines handle OS-specific initialization, and we've removed most of those, the one thing not removed is android initialization.

**Comment by DemiMarie** [comment]
In that case, is there a reason to require `ares_library_init` outside of Android?

**Comment by bradh352** [comment]
As of the current main branch, its a no-op.  However, that hasn't made it into any release as of yet.  Previously it had to dynamically load a bunch of windows libraries in order to dynamically support newer windows versions (to be able to pull DNS server lists and so on)... but those newer windows versions are now old windows versions today, so we got rid of that dynamic logic.  I think getting rid of those library init functions would be foolish as we could need to do similar things in the future to support newer systems, and then people would have to change their integration.
