### ISSUE TITLE
Feature request: easy way to disable tests that use network

### ISSUE THREAD

**Issue by dmacks** [c-ares/c-ares#455]
Building c-ares-1.18.1 on my OS X 10.13, I got some failures in arestest. My home ISP is known to do weird things with certain DNS requests, so I'm not entirely surprised, and I don't expect a test suite to be able to compensate for every result that a non-standard configuation might give. But for the record:
```
[==========] 473 tests from 22 test suites ran. (50854 ms total)
[  PASSED  ] 470 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Modes/DefaultChannelModeTest.LiveGetLocalhostByNameV6/0, where GetParam() = "f"
[  FAILED  ] Modes/DefaultChannelModeTest.LiveGetLocalhostByNameV6/2, where GetParam() = "fb"
[  FAILED  ] Modes/DefaultChannelModeTest.LiveGetLocalhostByNameV6/3, where GetParam() = "bf"

 3 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS
```

So I put it into a no-network sandbox environment, and:
```
[==========] 473 tests from 22 test suites ran. (51571 ms total)
[  PASSED  ] 448 tests.
[  FAILED  ] 25 tests, listed below:
[  FAILED  ] DefaultChannelTest.LiveGetHostByNameV4
[  FAILED  ] DefaultChannelTest.LiveGetHostByNameV4_virtualized
[  FAILED  ] DefaultChannelTest.LiveGetHostByNameV6
[  FAILED  ] DefaultChannelTest.LiveGetHostByNameV6_virtualized
[  FAILED  ] DefaultChannelTest.LiveGetHostByAddrV4
[  FAILED  ] DefaultChannelTest.LiveGetHostByAddrV4_virtualized
[  FAILED  ] DefaultChannelTest.LiveGetHostByAddrV6
[  FAILED  ] DefaultChannelTest.LiveGetHostByAddrV6_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchA
[  FAILED  ] DefaultChannelTest.LiveSearchA_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchNS
[  FAILED  ] DefaultChannelTest.LiveSearchNS_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchMX
[  FAILED  ] DefaultChannelTest.LiveSearchMX_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchTXT
[  FAILED  ] DefaultChannelTest.LiveSearchTXT_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchSOA
[  FAILED  ] DefaultChannelTest.LiveSearchSOA_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchSRV
[  FAILED  ] DefaultChannelTest.LiveSearchSRV_virtualized
[  FAILED  ] DefaultChannelTest.LiveSearchANY
[  FAILED  ] DefaultChannelTest.LiveSearchANY_virtualized
[  FAILED  ] Modes/DefaultChannelModeTest.LiveGetLocalhostByNameV6/0, where GetParam() = "f"
[  FAILED  ] Modes/DefaultChannelModeTest.LiveGetLocalhostByNameV6/2, where GetParam() = "fb"
[  FAILED  ] Modes/DefaultChannelModeTest.LiveGetLocalhostByNameV6/3, where GetParam() = "bf"

25 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS
```

I can do `GTEST_FILTER="-*.Live*"`, but that seems to omit over 100 tests, clearly too broad a pattern. Is there a tighter regex for only the ones that do *remote* (vs live local) access? Or else could there be a ./configure flag that passes an explicit list of them via that variable? Or could the relevant tests have an optional GTEST_SKIP() based on some special env-var?

**Comment by bradh352** [comment]
Using the gtest filter is the only way to exclude or run a set of tests.  I doubt that will change.  If they're not grouped properly, the test names should be changed to make it easier to group, I'd have to eval the test cases to see what they do.

However, I am curious as to why LiveGetLocalhostByNameV6 would be failing.  That was actually reworked in 1.18.1 with #430.  Those queries should never leave the local machine at all and basically always succeed.  

Can you provide more information on the failure? Do you have the test output?

**Comment by dmacks** [comment]
All three LiveGetLocalhostByNameV6 tests emit:
```
ares-test-live.cc:162: Failure
Expected equality of these values:
  1
  (int)result.host_.addrs_.size()
    Which is: 2
```
(same line-number and values), whether or not I have network available.

**Comment by dmacks** [comment]
Debian's packaging policy is that the build (including self-test targets) "must not attempt network access, except, via the loopback interface, to services on the build host that have been started by the build". So having either a way to catch them by `--gtest_filter` or or an env-var for optional skipping seems like it would help them also.

**Comment by bradh352** [comment]
filtering out any *Live* tests will do exactly that with gtest filter, so the capability for what you want is already there, its just not terribly convenient to use.

Now regarding your ipv6 failure, that appears to be something in /etc/hosts ... like you have 2 ip addresses assigned to 'localhost'.

**Comment by chengyechun** [comment]
ares-test-live.cc:298: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchNS (750 ms)
[ RUN      ] DefaultChannelTest.LiveSearchNS_virtualized
ares-test-live.cc:298: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchNS_virtualized (568 ms)
[ RUN      ] DefaultChannelTest.LiveSearchMX
ares-test-live.cc:307: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchMX (760 ms)
[ RUN      ] DefaultChannelTest.LiveSearchMX_virtualized
ares-test-live.cc:307: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchMX_virtualized (625 ms)
[ RUN      ] DefaultChannelTest.LiveSearchTXT
ares-test-live.cc:316: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchTXT (809 ms)
[ RUN      ] DefaultChannelTest.LiveSearchTXT_virtualized
ares-test-live.cc:316: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchTXT_virtualized (628 ms)
[ RUN      ] DefaultChannelTest.LiveSearchSOA
ares-test-live.cc:325: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11
[  FAILED  ] DefaultChannelTest.LiveSearchSOA (809 ms)
[ RUN      ] DefaultChannelTest.LiveSearchSOA_virtualized
ares-test-live.cc:325: Failure
Expected equality of these values:
  0
  result.status_
    Which is: 11

those testcase is failure, is it because needing network @bradh352

**Comment by bradh352** [comment]
@chengyechun Correct.

Either set the environment variable:  `GTEST_FILTER=-*Live*` before running tests, or if executing gtest directly, you can pass `--gtest-filter=-*Live*`.

Live tests all have the Live keyword in them and can be excluded in bulk.  Excluding Live tests will exclude any tests that depend on network or system configuration.
