### ISSUE TITLE
Optimize ares__readaddrinfo (or find a way not to call it)

### ISSUE THREAD

**Issue by bsergean** [c-ares/c-ares#458]
Hi there,

We just started to use c-ares (through libcurl), and we noticed a fair amount of time spent in ares__readaddrinfo.

It's not clear to me what is expensive yet, whether it's the disk IO or some computation inside the function itself.

```
$ wc -l /etc/hosts
7878 /etc/hosts
$ wc -c /etc/hosts
432830 /etc/hosts
```

Our host file is close to 500k, so definitely not a trivial amount of bytes to read.

```
>>> 432830 / 7878
54
```

1. Is it feasible to only read that file once, keep either a list of entries, or a hashmap if applicable ?
2. We can also just provide the content of the path as a memory buffer, and it would be up to the caller to detect when the file is changed, and re-read the /etc/host file from disk ?

I looked at the init options, and maybe we could already  for https://c-ares.org/ares_init_options.html

curl offers to tweak the c-ares resolver behavior thanks to https://curl.se/libcurl/c/CURLOPT_RESOLVER_START_FUNCTION.html
Is there anything we could do there.

I'd be happy to try something if time allows, if I can get some directions on a good thing to try it would be good.

**Comment by bradh352** [comment]
I don't think I necessarily have a problem with the idea of caching the /etc/hosts data.  Afterall, we cache the server configs (/etc/resolv.conf).  That said, I'd like to see an overall solution that would also reload the rest of the configuration as it has been a common request (Issue #301 remains open to track this).

**Comment by bsergean** [comment]
The linked ticket reference reloading the /etc/resolv.conf file, I looked at the proposed patch which was closed for lack of activity (https://github.com/c-ares/c-ares/pull/272/files).

Maybe a first piece of work would be to store the /etc/host data in memory (say a list of entries), and have are__readaddrinfo consume that. I don't know where the info from parsing the resolv.conf file lives, but maybe it could live close by.

**Comment by bsergean** [comment]
Since ares__readaddrinfo is internal, maybe we have more room in modifying it to the needs of this ticket.

**Comment by bradh352** [comment]
PR #272 did go stale and was a linux-only solution which unfortunately won't work for a cross-platform system.  It also would likely cause crashes or some undefined behavior if there were any outstanding requests due to changing the servers object out from under active requests that hadn't yet received replies.

**Comment by bsergean** [comment]
Got it. Maybe the simplest approach to make progress would be to be able to pass in the host data as memory buffer (a char*), rather than a file path.

The same approach is used in libcurl when supplying certificates. I will try to make a quick hack to see the speedup I’m getting with this approach.

**Comment by bradh352** [comment]
I sort of doubt the act of the file reading is going to be the main culprit.  By default fopen() and friends do buffered file accesses, and then you have the host OS cache for commonly accessed files.   Of course, I could be wrong on the % of impact.

**Comment by bsergean** [comment]
It's possible that the scanning takes time too, but parsing 500k of data certainly isn't free, in our case where our host files are big (managed by tool like chef). We see that ares_init_options is also taking time.

**Comment by bsergean** [comment]
Link to the function to optimize -> https://github.com/c-ares/c-ares/blob/c25d4eb767aa0beb9bda355f56b3c324668742b6/src/lib/ares__readaddrinfo.c#L35

**Comment by bsergean** [comment]
@bagder + @bradh352, would you be ok with the possibility to have a structure representing the result of parsing the /etc/hosts file be used, and set from curl ?

Not exactly sure what it would be, a list of things, a list of hosts ? ... / so ares__readaddrinfo would return this, and we would need another function that match hosts.

The current return type seems to populate a `struct ares_addrinfo *ai`.

**Comment by bagder** [comment]
Are you suggesting keeping a cached pre-parsed version of `/etc/hosts` in memory associated with the channel and reload from file only if etc-hosts has been changed? Seems like something worthwhile to test out. It should then probably only be done if the associated option is set asking for this behavior.

**Comment by bsergean** [comment]
Yes something along those lines.

The downside will be that storing the pre-parsed version of /etc/hosts might consume more memory than ’streaming’ / scanning through it, but the upside would be not repeating the parsing work. I looked again at our app and the runtime cost of readaddrinfo is quite high.

**Comment by bradh352** [comment]
What is provided probably needs to be a hashtable, or if that's too costly, a sorted list that you can use a binary search on, otherwise the scanning will still consume a lot of resources still.

Unfortunately c-ares doesn't currently provide any nice data structures for this purpose already.

**Comment by bsergean** [comment]
A 3 minutes google search found this C library for hash tables (I haven’t had to use C hash tables before, I mostly code in C++ where std::map and hash map come in the standard library), there are probably a bunch of good other ones.

https://github.com/anholt/hash_table

**Comment by bradh352** [comment]
yeah, there's tons of implementations out there of course.  I've even written them before ... https://github.com/Monetra/mstdlib/blob/master/base/hash/m_hashtable.c  the point is c-ares doesn't currently have stuff like that.

**Comment by bsergean** [comment]
Sure. So this task would require to pick a good hash-table implementation and bundle it with the library, or go with a sorted list approach if needed.

The link I found has just a few file, and the description of the library is (easy to embed) so this could be a good pick, as it would also be simple build-system-wide.

**Comment by bagder** [comment]
As the entries are read and parsed one-by-one, the question if it isn't enough to just put them in an sorted array (realloc'ed when growing) and then bsearch() that for lookup. It's a simple implementation and still a fast lookup.

**Comment by bagder** [comment]
Hm, maybe that is too slow to populate on second thoughts.

**Comment by bsergean** [comment]
We can try the simple implementation first, build the unsorted array on populate, and then sort with qsort when we’re done scanning/parsing. 

And search with bsearch afterwards. This way we don’t need to bring in a hash-table implementation.

If that approach is too slow we can use the hash table big gun.

**Comment by createyourpersonalaccount** [comment]
I'm giving this a shot but my progress has been encumbered by a very restrictive timetable. I'd just like to report some findings:

- The current state of things is that the `/etc/hosts` file is read every time and an O(n^2) algorithm is used to identify aliases for hostnames. We could use a better algorithm, like hash tables or binary search and cache the file contents as improvements.
- I decided to use hash tables. I couldn't find any fast, MIT-license-compatible, C89, 32-bit compatible, hash-flood-resistant hash table implementations: The difficulty is in choosing the hash algorithm. I am not a cryptographer (but I do have some awareness) and I thought Python's approach would be a good one to follow, see [PEP 456](https://peps.python.org/pep-0456/#examined-hashing-algorithms) which outlines the requirements of their hash function for hash tables and their approach. However, Python doesn't care about C89, which makes it tricky to use modern hash functions like SipHash because e.g. the [SipHash reference implementation](https://github.com/veorq/SipHash) uses C99 exact-width integer types like `uint32_t`. The qsort/bsearch approach is easier to accomplish for this reason.
- I couldn't find a platform-independent file handling API. I only need modification times in order to cache the results of `/etc/hosts`. I was going to write my own function; I've only recently realized I still have access to Windows images via my firmware-baked key from this recently purchased laptop, so this is work in progress too. I think for Linux, BSD, Mac and Android the approach is the same (POSIX). Furthermore, while all the functions that need to be modified are internal, they unfortunately interact with public structs. Some thought needs to be given as to where the cache is stored if one wants to avoid a version bump for ABI incompatibility, which I haven't yet had time to think about.

**Comment by bradh352** [comment]
@bsergean mind checking PR #591 to see if this addresses your issue?

**Comment by bradh352** [comment]
fixed in PR #591

**Comment by bsergean** [comment]
Thanks a lot for implementing that @bradh352 ; I'm not sure when I'll have the time to try this.

From looking briefly at the PR it looks like no public headers were changed, so this should all be internal and not require any changes on the app side. Probably we should try to keep some objects around when doing multiple requests if we don't want the cache/hash-map to be deleted ?

**Comment by bradh352** [comment]
Its cache'd into the ares_channel object, as long as that channel persists (which is the recommended practice), the cache will be used until it is invalidated by a change to the hosts file.

It looks like you were using curl for this, so you may need to work with the curl guys on the persistence of that ares_channel object into the curl_multi_*() or similar to ensure the cache within c-ares can be used.
