### ISSUE TITLE
should the "||" be replaced with "&&"  at the line 632 of the source file ares_process.c? 

### ISSUE THREAD

**Issue by exactao** [c-ares/c-ares#472]
below code segement is at the line 628 of the source file ares_process.c, 

  ```
/* If we got a truncated UDP packet and are not ignoring truncation,
   * don't accept the packet, and switch the query to TCP if we hadn't
   * done so already.
   */
  if ((tc || alen > packetsz) && !tcp && !(channel->flags & ARES_FLAG_IGNTC))
```

should "||" be replaced with "&&" ?

**Comment by bradh352** [comment]
not as far as I can tell by looking at the code.  Why?

**Comment by exactao** [comment]
Because the code is not consistent with the comments below.  If a response received by a client is a truncated UDP packet as said in the comments,  in the right case "tc" shoud be 1 and "alen" should be less than or equal to 512, but in the abnormal case "tc" also should be 1 and "alen" should  be large than 512.  in other words, if the reponsed packet is not truncated( "tc" is not 1), there is nosense to check the value "alen".  If any misunderstand, please correct me.

**Comment by bradh352** [comment]
The purpose of this code is to determine when we should ignore the current response and retry our request via TCP instead.

The maximum UDP packet size allowed for DNS is 512 bytes ... so if we have more than 512 bytes in an answer, it is assuming it is most likely corrupt and will force it to use TCP instead of trying to interpret the current response.

It is probably impossible for both `tc` to be set and the packet size to be LARGER than 512 bytes, so changing this to && would never upgrade to TCP from UDP when the response size would be larger than UDP can handle, which would be really bad.

**Comment by exactao** [comment]
itis not true “The maximum UDP packet size allowed for DNS is 512 bytes“，we have met the peoblem. otherwise tc is not useful for udp dns package and we should not check it in the code.

**Comment by bradh352** [comment]
Care to provide more information other than stating it is incorrect?

This provides the limitation:
https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.4

EDNS does allow negotiation of higher, but it has been proven that fragmentation occurs and can be unreliable across the public internet.

Are you trying to report some sort of reproducible bug?   If so, you should start there.

**Comment by exactao** [comment]
Yes. I update my previous comments.

**Comment by bradh352** [comment]
Ok, i see your updated comment now.  

`tc` is a flag in the message header, sent by the DNS server, stating the message is truncated, not something "derived".  So If it is specifically stating the server truncated the message to fit in the packet, there's no way the message should exceed 512 bytes unless the server is completely bonkers.  The existence of the tc flag tells c-ares it MUST retry via TCP.

c-ares is then also checking to make sure the message isn't greater than 512 bytes because corruption is likely and therefore we cannot trust the response, thus we must also retry via TCP in this condition.

So these are definitely different conditions and || is appropriate not && as they would not be true together.

Do you have a specific error condition that needs to be evaluated?  If not, then I don't see any reason to continue this discussion.  If you do have a test case that is legitimate, please share so we can evaluate.

NOTE: I'm using 512 bytes as a placeholder here, if ARES_FLAG_EDNS is set, it uses either the default of 1280 or ARES_FLAG_EDNSPSZ's provided size in the sanity check.  Any packet greater than either the DNS maximum UDP packet size or the EDNS negotiated packet size for UDP must be treated as bad.

**Comment by exactao** [comment]
our problem is very simple，a Tencent DNS 
 server sent a response in which the tc is zero and
 the packet size is larger than 512. So the TCP request was sent, but the server does not support tcp querry and the querry was fail in the end. we think ARES_FLAG_EDNS is not set, because cares is invoked by curl, we did not find it set in libcurl source code neither there is any option can control it.
But just as you said it should not happen when both tc is 1 and udp packet size exceed the maximum payload size, so we should check them both but not either one of them, right? 
do you think in udp response, tc should not be 1?

**Comment by bradh352** [comment]
tc is meant to be set by the dns server stating they couldn't send a full reply so its truncated.  If the flag isn't set, that means they think the DNS response packet size is legitimate, but c-ares says, no it can't be, and retries the query using TCP instead of UDP.

DNS servers are required to support TCP for this exact reason.  I seriously doubt Tencent doesn't support DNS over TCP, more likely is you have some firewall rule blocking TCP port 53, which is a network configuration error.

Otherwise the only solution is to explicitly enable EDNS in c-ares to allow larger packets to work around the condition, but for that you would need to ask curl to provide configuration to tune their usage of c-ares.  (That said, I'm not entirely sure why EDNS isn't the default these days).

**Comment by exactao** [comment]
May I think below comments means wether the flag is set or not, if the UDP response payload size exceeds the maximum size ( supports
ARES_FLAG_IGNTC is not set),  c-ares alway think it is not legitimate?

"If the flag isn't set, that means they think the DNS response packet size is legitimate, but c-ares says, no it can't be, and retries the query using TCP instead of UDP."

**Comment by bradh352** [comment]
correct, regardless of the tc flag, if the udp payload is larger than 512 for non-EDNS, or larger than ARES_FLAG_EDNSPSZ (or 1280 by default) when using EDNS, it is not a legitimate response as per the standard.

**Comment by exactao** [comment]
Ok. Just from the view of code logic, If so, it seems better to not check tc in the code.
I have to ask for help from the curl
