### ISSUE TITLE
Adding mutex to protect functions using global variable ares_initialized 

### ISSUE THREAD

**Issue by yanjunxiang-google** [c-ares/c-ares#475]
In ares_library_init() and ares_library_cleanup(), it is using the static global variable ares_initialized to guard the behavior:

https://github.com/c-ares/c-ares/blob/afee6748b0b99acf4509d42fa37ac8422262f91b/src/lib/ares_library_init.c#L87

https://github.com/c-ares/c-ares/blob/afee6748b0b99acf4509d42fa37ac8422262f91b/src/lib/ares_library_init.c#L56

However, this won't work in multi-thread system since these functions are not atomic.  We should make these two functions atomic, something like below:

+++ /ares/ares_library_init.c	
@@ -15,12 +15,15 @@
@@ -36,6 +39,7 @@ 
 /* library-private global vars with source visibility restricted to this file */
 
+pthread_mutex_t ares_initialized_lock = PTHREAD_MUTEX_INITIALIZER;
 static unsigned int ares_initialized;
 static int          ares_init_flags;
 
@@ -129,6 +133,7 @@
 {
   int res;
 +  pthread_mutex_lock(&ares_initialized_lock);
   if (ares_initialized)
     {
       ares_initialized++;
@@ -144,7 +149,7 @@
     }
 
   ares_init_flags = flags;
+  pthread_mutex_unlock(&ares_initialized_lock);
   return ARES_SUCCESS;
 }
 
@@ -165,6 +170,7 @@
  void ares_library_cleanup(void)
 {
+ pthread_mutex_lock(&ares_initialized_lock);
   if (!ares_initialized)
     return;
   ares_initialized--;
@@ -182,6 +188,7 @@
   ares_malloc = malloc;
   ares_realloc = realloc;
   ares_free = free;
+ pthread_mutex_unlock(&ares_initialized_lock);
 }

**Comment by dimbleby** [comment]
previously rejected at #449.  

fwiw I agree that c-ares would be better if it were thread-safe rather than offloading that responsibility to users: but be aware that you'll probably have to make the case more convincingly than that if you want to persuade maintainers.

**Comment by bradh352** [comment]
c-ares has no threadsafety built in at all.  Trying to add it in one place, initialization, does not solve all the other instances lacking thread safety.  Also, it is common for libraries to not allow multi-threaded initialization in the first place, where the caller must guarantee that.  A lot of times, the initializer involves setting up the environment-specific thread-safety callbacks and whatnot.  Your proposed patch doesn't handle this nor does it handle, say, Windows, which lacks pthreads support.  So adding thread-safety to the library if a full patch is added might be accepted, it is doubtful you could portably do this for initialization in the first place.

**Comment by dimbleby** [comment]
Not in defence of this patch in particular, but it's notable that curl - which of course has a sort of family relationship with c-ares - has recently headed in this general direction: https://daniel.haxx.se/blog/2022/06/08/making-libcurl-init-more-thread-safe/

**Comment by bradh352** [comment]
curl is definitely in more active development than c-ares.  There's a lot of stuff in c-ares that probably needs to be modernized, but more than init needs to be made threadsafe ... to solve some of the issues, c-ares really needs a completely new API then have the old API as a compatibility layer on top of it.

**Comment by dimbleby** [comment]
Not to disagree with what you're saying, but I do think that the initialisation stands out as a particular wart.  

My perspective is as maintainer of rust bindings to c-ares, where almost everything Just Works if I make most methods on the channel be via a `mut` reference: then the rust compiler will guarantee that thread-unsafe usage is not possible.

But initialisation is more awkward...

**Comment by bradh352** [comment]
I think other than Android, library initialization is meaningless these days.  I had cleaned that up a release or two back.

**Comment by jmarantz** [comment]
It would be helpful to get an understanding from the c_ares maintainer whether (putting aside init/shutdown races) the library can be used from multiple threads if no API-visible data structures are shared across threads. Typically we call that *thread-compatible*. strcpy is an example of such a function. The only reason I can think of this would *not* be the case is if there is more hidden state.

The existing ares init/shutdown functions are what we tend to call *thread-hostile*, like strtok. They operate on hidden state in a thread unsafe way. In our environment we have two entirely unrelated subsystems that need to init/shutdown c_ares from different threads. The two systems are controlled by teams that do not know about each other and cannot reference one another's code directly.

I understand the proposed patch is not portable, but it seems not too hard to port it to Windows with ifdefs or whatever.

**Comment by bradh352** [comment]
the only thing the library initialization ever did was on Windows, it would do run-time loading of APIs depending on Windows versions.  Now that those windows versions are EOL, we dropped support for runtime loading of those thus making the init routes no-ops.  Granted, Android support was introduced which required a Java JVM be bound in order to access Java-only functions, so that is the only Global anymore.

Otherwise, the ares_channel contains everything, and must not be accessed by more than 1 thread at a time (granted if you properly use mutexes and whatnot for accessing the channel, you can share it across threads).  One thing to remember is c-ares uses a callback system, and the ares_channel is in use when a callback is called.

**Comment by jmarantz** [comment]
It's a relief to hear that if we can avoid the init races between subsystems oblivious to one another, we'd have no races operationally as long as we don't share channels between threads without mutexing.

So the problem is that one of the code-bases (the Envoy proxy) actually does run on Windows and Android. So it needs to init on those platforms. What is the issue with having making c_ares init thread compatible? It seems like Yanjun's code snippet would be a plausible starting point if a windows-native alternative to the pthreads mutex were injected via ifdef.

It doesn't sound like any other changes would be needed for c_ares, as protection around any sharing of the data structures is well under control of the calling application.
