### ISSUE TITLE
CMake config files are not installed when building with autotools

### ISSUE THREAD

**Issue by nicolasfella** [c-ares/c-ares#482]
When building c-ares with CMake the following files are installed:
<prefix>/lib64/cmake/c-ares/c-ares-targets.cmake
<prefix>/lib64/cmake/c-ares/c-ares-targets-noconfig.cmake
<prefix>/lib64/cmake/c-ares/c-ares-config.cmake
<prefix>/lib64/cmake/c-ares/c-ares-config-version.cmake

These files allow consumers using CMake to find/import c-ares using `find_package(c-ares)`.

However, when building c-ares using the autotools buildsystem these files are not installed, meaning consumers cannot find/import c-ares that way.

Some Linux distributions build c-ares using CMake while others build it using autotools. This produces inconsistent and surprising behavior for consumers of c-ares. Consumers should not need to know or care how a library was built in order to use it.

**Comment by bradh352** [comment]
Unfortunately these are autogenerated by the cmake build process, I don't think there's any way to easily generate these with autotools and I'm not really aware of any other libraries that do this that support both build systems.

My best recommendation is to implement a custom c-ares find package script in the build system of the package depending on c-ares rather than assuming anything at all exists on the system.  One such example is here:
https://github.com/Monetra/mstdlib/blob/master/CMakeModules/Findc-ares.cmake

**Comment by dfandrich** [comment]
Why can't a cmake-using application use pkg-config to find and use 
c-ares? That should be available no matter how c-ares is built.

**Comment by nicolasfella** [comment]
> Why can't a cmake-using application use pkg-config to find and use c-ares? That should be available no matter how c-ares is built.

CMake-using apps can use pkg-config. That is what we are doing in my project now, but only after learning about this limitation the hard way

**Comment by dfandrich** [comment]
What's the problem with using pkg-config?

**Comment by bradh352** [comment]
agreed, pkg-config seems like a reasonable solution here.
