### ISSUE TITLE
Consider unbundling external Googletest library

### ISSUE THREAD

**Issue by diizzyy** [c-ares/c-ares#506]
This seems to be unnecessary especially since it's not being kept up to date?
As a side note, it works fine using upstream release 1.12.1 (https://github.com/google/googletest/releases/tag/release-1.12.1)

**Comment by bradh352** [comment]
right now c-ares has no external dependencies for building, running, or testing.  Introducing an external dependency would require quite a bit of thought, and could cause additional support headaches.  Is there any particular issue that spawned this request other than it not being the latest bleeding edge version?  Since its just a test framework, there's no security risk involved with it being out of date.

**Comment by diizzyy** [comment]
In general when it comes to package repos it's preferred not to have bundled libraries because it's much easier to keep track of upstream, regressions, build and security issues. Additionally it also saves a processing power when scaled, you don't need to keep recompiling it which also would save you a bit of time running CIs. Googletest also provides both .cmake and .pc files so version handling isn't an issue and it'll be easy to integrate.

It's packaged in pretty much all available repos
https://repology.org/project/gtest/versions

See https://archlinux.org/packages/community/x86_64/gtest/ for example.
It's also done by a bunch of projects already (FreeBSD also deploys this practice for example but "unit test"-dependencies are not listed as regular build deps so you need to grep the ports tree).

**Comment by bradh352** [comment]
fixed in #655

**Comment by diizzyy** [comment]
Thanks!
