### ISSUE TITLE
c-ares doesn't use dns suffix in the system.

### ISSUE THREAD

**Issue by peterlaser** [c-ares/c-ares#53]
windows OS
1. Open the Advanced TCP/IP settings dialog.
2. Append the DNS suffixes
3. Use App/c-ares1.10 connect to the web server name without the DNS suffix.

Result:
Failed to connect to the web server.
Have to use FQDN to connect to the web server.

ares_init.c, Line 1609

static int init_by_defaults(ares_channel channel)
{
  …
  // Need to Add code to find the suffix!

  if (channel->ndomains == -1) {
    /\* Derive a default domain search list from the kernel hostname,
     \* or set it to empty if the hostname isn't helpful.
     */
# ifndef HAVE_GETHOSTNAME

```
channel->ndomains = 0; /* default to none */
```
# else

**Comment by daviddrysdale** [comment]
On a quick look, the most obvious place to retrieve the search domain list would be to extend `get_DNS_AdaptersAddresses()` because this already calls `GetAdaptersAddresses` and the returned [IP_ADAPTER_ADDRESSES](https://msdn.microsoft.com/en-gb/library/windows/desktop/aa366058(v=vs.85).aspx) structure includes a `FirstDnsSuffix` field connecting to a linked list of [IP_ADAPTER_DNS_SUFFIX](https://msdn.microsoft.com/en-gb/library/windows/desktop/bb613464(v=vs.85).aspx) structures.

However....the `FirstDnsSuffix` field is only present for Windows versions >= Vista+SP1/Server-2008, so that would need some sort of version-specific code.

(The only other methods for getting the search list seem to involve [registry spelunking](http://stackoverflow.com/questions/16165629/how-to-get-windows-dns-suffix-search-list-using-c).)

**Comment by bradh352** [comment]
resolved via PR #93
