### ISSUE TITLE
Failed to launch App if the client host leave the DNS field blank

### ISSUE THREAD

**Issue by peterlaser** [c-ares/c-ares#60]
Steps:
1. Client machines not joined to domain and only one NIC.
2. In Windows Network and Internet setting, Specify IP address explicit and leave the DNS server field blank in the IPv4 settings
3. Launch App which use libcurl/c-ares 1.11

Result:
App failed to launch.

Note:
c-ares 1.10 doesn't have the issue.

Workaround
Join client machine to the domain or populate the IPv4 settings with a DNS server, does not have to be a valid IP address, or more than one NIC

![ares_init c](https://cloud.githubusercontent.com/assets/11938491/17200474/3e0b20e2-54b8-11e6-8d96-7e80e5b3890c.png)

**Comment by daviddrysdale** [comment]
This behaviour change was introduced in commit 46bb820be3a8, but you're right it probably went too far -- it's probably sensible for an `ARES_EFILE` failure from `init_by_resolv_conf()` to be overridden by a subsequent `init_by_defaults()`.

However, the original change is definitely needed in some contexts -- if the user explicitly specified some options, any failure to apply them in `init_by_options()` should be reported.

So I'd suggest just preserving `init_by_options()` failures and reverting to the previous behaviour otherwise. I've put a suggested fix in [pull 61](https://github.com/c-ares/c-ares/pull/61) -- could you check that works in your scenario?

**Comment by daviddrysdale** [comment]
I believe this is fixed by commit 55bbe92677e4aca
