### ISSUE TITLE
c-ares tag issue

### ISSUE THREAD

**Issue by toast12** [c-ares/c-ares#67]
Hi,

All the c-ares tags have -DEV suffixed to the version number in ares_version.h as follows:

#define ARES_VERSION_STR "1.11.1-DEV"

Why is that? The release tarballs do not have a -DEV in there.

**Comment by bagder** [comment]
Because you're using tagged source code and not the release tarballs. The tarballs contain the releases, the git repository is tagged so that you can get all the files exactly as they were at the time of the release. We don't commit generated files and the release process generates a few files that get included in the release tarball.

**Comment by toast12** [comment]
Thanks. We use git repo for our internal builds. So if I want to fix this internally, what is the most sustainable approach? I read in your libcurl forum that you run a build configuration utility. If I run it, will that fix this issue?

**Comment by toast12** [comment]
Following up. Badger, can you please suggest?

**Comment by toast12** [comment]
Hi Badger, can you provide an updated maketgz to update version number only? This is same as https://github.com/curl/curl/issues/1076
