### ISSUE TITLE
Compiling libcurl on Mac and using c-ares yields the following erro

### ISSUE THREAD

**Issue by wucaizi** [c-ares/c-ares#675]
ld: Undefined symbols:
  _res_9_getservers, referenced from:
      _ares__init_sysconfig_libresolv in libcares.a[69](ares_sysconfig.c.o)
  _res_9_ndestroy, referenced from:
      _ares__init_sysconfig_libresolv in libcares.a[69](ares_sysconfig.c.o)
  _res_9_ninit, referenced from:
      _ares__init_sysconfig_libresolv in libcares.a[69](ares_sysconfig.c.o)

**Comment by bradh352** [comment]
Since you're linking to the static version of c-ares, you need to specifically specify the libraries that c-ares depends on.  Typically you'll use pkg-config to get that stuff automatically, as you can see on MacOS the generated libcares.pc has:
```
#***************************************************************************
# Project        ___       __ _ _ __ ___  ___ 
#               / __|____ / _` | '__/ _ \/ __|
#              | (_|_____| (_| | | |  __/\__ \
#               \___|     \__,_|_|  \___||___/
#
# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
prefix=/usr/local
exec_prefix=/usr/local/bin
libdir=/usr/local/lib
includedir=/usr/local/include

Name: c-ares
URL: https://c-ares.org/
Description: asynchronous DNS lookup library
Version: 1.24.0
Requires: 
Requires.private: 
Cflags: -I${includedir}
Libs: -L${libdir} -lcares
Libs.private:  -lresolv
```

Which Libs.private has -lresolv saying that's an additional library you need to include when linking.
