### ISSUE TITLE
Feature: Disable parsing of known RR type

### ISSUE THREAD

**Issue by eriklax** [c-ares/c-ares#686]
If it's not possible (and I was really digging deep). It would be useful if you could force ares_dns_parse() or ares_dns_rr_get_XX to NOT parse a rrtype response and known RR type and allow it to end up as ARES_RR_RAW_RR_DATA (as it were unknown). I want to do custom parsing of the RR data that is known to c-ares using the same API.

**Comment by bradh352** [comment]
That should be trivial to add a flag for the parser to do that.  The real issue, however, is for name expansion for the RRs that RFC1035 allows the use of name compression for.  You wouldn't have the ability to just extract the RR itself and parse it independently without the rest of the data due to back references.

Out of curiosity, what is the exact use case?  The new parser is fairly robust, just want to know where it may be lacking.

**Comment by eriklax** [comment]
I'm migrating a resolver function in a (DSL) scripting language from libresolv (with custom parsers) to c-ares. It currently have a more limited RR type support than c-ares, so for types such as "TLSA", the user would expect to receive raw data and unpack it himself. This makes it hard to implement, since c-ares parses this data and I the user expects it unparsed (raw bytes).

While I could undo the parsing, and pack the data again I don't later versions of c-ares to add support for more DNS-types than I've implemeneted (hence breaking the raw fallback in the future).

I'm not conserned about name compression and back references.

**Comment by bradh352** [comment]
sure, should be pretty trivial to get into the next release

**Comment by eriklax** [comment]
Thanks, that would be so appreciated. It was so great that the parser and writer API was made public!

**Comment by eriklax** [comment]
As per the PR, for my use-case only `ARES_DNS_PARSE_ANSWER_RR_RAW` is needed. But I think it could make sense to allow disabling parsing of all three types for completeness (either invidual) or all together implementing only a `ARES_DNS_PARSE_RR_RAW` flag.
