### ISSUE TITLE
AAAA response handling

### ISSUE THREAD

**Issue by jkemp101** [c-ares/c-ares#73]
When AWS returns a NS record for a AAAA query the c-ares library interprets this as an invalid response and retries the AAAA query using the search list.  This causes the original query to not be properly resolved and results in unnecessary additional queries for each search list domain.

I took another look at the packet trace and it looks like this also happens when the AAAA record is no host.  I think ares should be happy with the valid IPv4 response and still not start using the search list.

**Comment by daviddrysdale** [comment]
If I'm understanding this right, I'd word it as essentially:

  "c-ares does not stop iterating through the search list when a NODATA response (which indicates that the name is valid but doesn't have records of the requested type) is received."

cf. [Paul Marks' earlier query](https://c-ares.haxx.se/mail/c-ares-archive-2015-03/0009.shtml), which noted that this looked like [long-standing/intentional behaviour](https://github.com/c-ares/c-ares/blob/master/ares_search.c#L148).

**Comment by bradh352** [comment]
Use ares_getaddrinfo() if you want to query for both A and AAAA records.   There was no supported means of mixing ipv4 and ipv6 prior to this in a single query.
