### ISSUE TITLE
Provide a symbol in ares_build.h to indicate if threads are present at compile time

### ISSUE THREAD

**Issue by johnthacker** [c-ares/c-ares#741]
`ares_threadsafety()` can be checked at runtime to see if threads are supported and if ARES_OPT_EVENT_THREAD is expected to work. It always returns ARES_TRUE if CARES_THREADS is defined when building, and ARES_FALSE if not.

It would be handy to have something like CARES_THREADS in ares_build.h so that applications could check at compile time if threading support is present. I'd like to use EventThreads to replace some deprecated functions, but since even recent versions of c-ares can be compiled with threading support off, that means getting compiler warnings for the codepath that handles the `ares_threadsafety() == ARES_FALSE` case, even if the version of c-ares being compiled against does support threading.

**Comment by bradh352** [comment]
I think the problem with this is with dynamic linking, having such a condition in `ares_build.h` may lead to circumstances to where it is wrong if a different variant of the shared library is put in place.

I think its a great idea to use the new event threads as we'll be adding more features in future versions, such as detecting system configuration changes automatically which won't be available to any code not using event threads.

**Comment by bradh352** [comment]
Yeah, I could see mandating threading support on platforms which support it.  The overhead of locking is extremely low when uncontested, which is expected to be the normal case for existing integrations (as if its not, they've been misusing it and are likely to crash).

There may be some legacy platforms where threading isn't available (though I'm not sure if they're tested, ever at this point, such as FreeDOS).  Also, I think Windows versions prior to 8 (7, Vista, XP, Server 2008) are unsupported in c-ares right now if you enable threading (that said, we don't actually provide a way to target older versions of windows, so if someone is, they're applying their own patches).  If these platforms don't matter to you, then I think you can probably kill all the legacy code.  Since compiling with threading is the default, and I haven't seen any OS distributions specifically compile without such support, you might just be able to get away with a sanity check of `ares_threadsafety()` during initialization and bail with an appropriate message.

To my knowledge, the only user of c-ares that disables threading is the rust wrapper (https://github.com/dimbleby/rust-c-ares) but they build and statically link.

**Comment by johnthacker** [comment]
The old Windows versions are out of all support by Microsoft and we don't support compiling Wireshark with them, so it's probably reasonable to just bail on c-ares support in Wireshark if `ares_threadsafety()` is false during initialization.

**Comment by bradh352** [comment]
going to close this since I think the suggestion was a reasonable workaround
