### ISSUE TITLE
Missing chain of trust for releases >= 1.30.0

### ISSUE THREAD

**Issue by dvzrv** [c-ares/c-ares#829]
Hi! :wave: 

I package this project for Arch Linux.
We usually track upstream sources using an nvchecker setup. This is [also the case for c-ares](https://gitlab.archlinux.org/archlinux/packaging/packages/c-ares/-/blob/8d64c54b030dbb49845a5fcc0e89d709a00f620e/.nvchecker.toml).
As the tagging scheme has been changed from `cares-$version` to `v$version` I did not notice there being new versions out right away.

Additionally, if available, we track and lock upstream OpenPGP certificate fingerprints (see https://gitlab.archlinux.org/archlinux/packaging/packages/c-ares/-/blob/8d64c54b030dbb49845a5fcc0e89d709a00f620e/PKGBUILD#L24).
In c-ares's case we have been locking @bagder 's `27EDEAF22F3ABCEB50DB9A125CC908FDB71E12C2`. 
Up until now we have used this certificate to verify the release tarballs of all c-ares releases.

With version > 1.30.0 I am unfortunately unable to establish a chain of trust between releases prior to 1.30.0 and 1.30.0 and beyond.

With 1.30.0, the README.md has been updated to include a verification section (https://github.com/c-ares/c-ares/blob/v1.30.0/README.md).
This section has unfortunately been added in an unsigned commit by @bradh352, whose OpenPGP certificate with the fingerprint `DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA` is used for signing release artifacts of all new releases (>= 1.30.0).

@bagder can you please create and publish a third-party certification (aka. "sign the key") for a User ID on @bradh352's OpenPGP certificate with the fingerprint `DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA`, so that we can validate the chain of trust?

If you need assistance with any of this, feel free to reach out.

The current situation blocks me from upgrading the package for Arch Linux.

**Comment by bradh352** [comment]
I agree, it would be prudent to do this, especially given the whole xz fiasco. Not that key signing was related to that, but does reflect on the whole supply chain issue at large.

@bagder I'm open whenever you want for a video chat so you can verify my government-issued IDs and whatnot if you think that's necessary for the signing ceremony.

**Comment by bagder** [comment]
I may need some step-by-step directions because I'm certainly not the wizard on this stuff, but we should certainly make sure to fix this, yes.

**Comment by bradh352** [comment]
@bagder as far as I'm aware, the basic proper steps are:
1. SIGNER: Verify the 3rd party individual is who they say they are (usually via Gov't issued ID, or some other means you're comfortable with), either in person or via video chat are typically recognized methods.  During this verification process, make sure you get their GPG key fingerprint (typically only the last 8 characters of the fingerprint are needed, not the whole 40 characters or whatever it is).
2. SIGNER: Retrieve the GPG public key for the party you are signing, typically you'd download this from a public keyserver, but it could be exchanged via other means.  For instance, mine is can be retrieved via: `gpg --keyserver hkps://keys.openpgp.org --recv-keys DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA`
3. SIGNER: You would then sign the key using your own, e.g. to sign mine you'd do something like: `gpg --sign-key --ask-cert-level DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA`
   - If full id verification was done, you'd choose option `3` saying `I have done very careful checking.`, otherwise one of the  other options.
4. SIGNER: You would then export the signed public key, I personally think just `gpg -a --export DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA >  DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA.asc` is sufficient, but they typically say you should also encrypt it before sending which would mean `gpg -a --export DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA | gpg -se -r DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA > DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA.asc.pgp` ... I'm not sure how that's actually necessary since the signature itself is cryptographic....
5. SIGNER: Then email that exported signed public to the 3rd party for which you signed their key, for me, that is brad@brad-house.com
6. RECEIVER: The 3rd party would then import that public key which will merge that signature into their public key: `gpg --import DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA.asc`
    - If it was sent encrypted, the 3rd party would need to first decrypt, e.g.: `gpg --decrypt DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA.asc.pgp`
7. RECEIVER: The 3rd party would then re-send their keys to the appropriate key servers so that future requests for those keys would include the signature:
```
gpg --keyserver hkps://keys.openpgp.org --send-keys DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA
gpg --keyserver hkps://keyserver.ubuntu.com --send-keys DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA
```

**Comment by dvzrv** [comment]
@bradh352 I generally agree with your assessment.

FWIW: The signer can just directly send the updated certificate to the keyserver (skip step 4-6 and have the signer do the step 7).
The receiver can then simply do a `gpg --recv-keys DA7D64E4C82C6294CB73A20E22E3D13B5411B7CA` and import the new certification :)

Do note, that keys.openpgp.org does *not* support third-party certifications (so the added certification will not be available from that keyserver).
It is generally advised to also upload to a synchronizing keyserver (such as pgpkeys.eu), as keyserver.ubuntu.com is not AFAIK (see e.g. https://wiki.archlinux.org/title/OpenPGP#Keyserver for details).

Not trying to be nitpicky, but I recommend not using the term "GPG key" and instead use "OpenPGP key". GnuPG at this point can unfortunately be considered tooling adversarial to the OpenPGP standard and its main developer is knowingly introducing breaking changes, conflicting with the upcoming RFC9580, that basically all other OpenPGP implementations follow.

**Comment by bradh352** [comment]
@dvzrv pretty sure its frowned upon for the signer to send the keys to the keyserver, or at least I read that somewhere, maybe that's a historic footnote.

Interesting, I've never heard of pgpkeys.eu, but I can definitely upload there.

**Comment by bradh352** [comment]
@dvzrv Just wanted to confirm the key signing we performed was sufficient for your needs.

**Comment by dvzrv** [comment]
Thanks! This works for me!
I'll update the package as soon as I have access to a build machine again.
