### ISSUE TITLE
ares_getsock needs documentation and examples

### ISSUE THREAD

**Issue by ctrix** [c-ares/c-ares#98]
I was trying to understand  ares_process_fd() and it seems, in the current documentation, that there is no way to get the ares_socket_t of a channel.

Watching at the sources, it seems that there is an ares_getsock() function that should fit this purpose but it lacks documentation. Quite weird, as it seems that it was added back in 2010.

Please add documentation and a meanungful example.

**Comment by bagder** [comment]
It was actually added in 2005. And what's perhaps more funny, so was the [docs](https://c-ares.haxx.se/ares_getsock.html).

**Comment by ctrix** [comment]
Sorry! You're right.
Kind to show an example about how to use it ?

**Comment by bagder** [comment]
I thought the functionality is pretty straight-forward. It is similar in spirit to `ares_fds()` but instead of filling in `fd_set` sets it returns the plain sockets and bits for what action to wait for on each respective socket.

If you provide a first embryo for an example based on how you think it works. I'll assist.
